#!/bin/bash

# ============================================================================= #
# ============================================================================= #
#                                                                               #
#                   ##########################################                  #
#                   ## <><><><><><><><><><><><><><><><><><> ##                  #
#                   ## <><><> MySampler Build Script <><><> ##                  #
#                   ## <><><><><><><><><><><><><><><><><><> ##                  #
#                   ##########################################                  #
#                                                                               #
# ============================================================================= #
# ============================================================================= #

# ----------------------------------- CONFIG -----------------------------------

PROJECT_NAME="MySampler"

MYSAMPLER_REPO=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );

ALL_BUILDS_DIRECTORY=$MYSAMPLER_REPO/mysampler-builds

DEBUG_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/debug-build

PRODUCTION_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/production-build

MYSAMPLER_INSTALL_PREFIX=/usr/local

# ----------------------------------- OPTIONS -----------------------------------

VERBOSE=false;

SILENT=false;

BUILD=false;

CLEAN_BUILD=false;

PITCH_DETECTION_ALGO="YIN";

DEBUG_BUILD=true;

ENABLE_GPU=false;

USE_GCC=false; # Clang is the default compiler

ABORT_AFTER_FIRST_TEST_FAILURE=false;

RUN_TESTS=false;

ONLY_RUN_FAST_TESTS=false;

LIST_TESTS=false;

USE_LOG=false;

###########################################################################################
# stdout helper functions
###########################################################################################

print()
{
    if [ "$SILENT" = false ]; then
        echo "$@"; 
    fi 
}

print_newline()
{
    print;
}

print_build_info()
{
    print " # [BUILD::INFO] | $@"; 
    print_newline;
}

verbose_print_build_info() 
{
    if [ "$VERBOSE" = true ]; then 
        print_build_info "$@";
    fi
}

verbose_print_stdin_command()
{
    if [ "$VERBOSE" = true ]; then
        echo " # [BUILD::STDIN] | $@"; 
        print_newline;
    fi
}

print_n_times()
{
    if [ "$SILENT" = false ]; then
        for i in $(seq $1); 
            do echo -n $2; 
        done;
    fi
}

print_divider()
{
    print_n_times 50 "<>"; 
    print_newline;
}

print_header_message()
{
    if [ "$SILENT" = false ]; then
        header_message="$@";
        message_length=${#header_message};
        line_length=100;
        indent=$((($line_length-$message_length-2)/2));

        print_newline;
        echo -n "|";
        print_n_times $indent "-";
        echo -n " $header_message ";
        print_n_times $indent "-"; echo "|";
        print_newline;
    fi
}

exit_with_error_message() 
{
    print_newline; 
    echo " # [BUILD::ERROR] | $@";
    print_newline; 
    exit;
}

print_help_message() 
{
    echo "options:";
    echo "v   Print out verbose information";
    echo "s   Supress cmake output";
    echo "b   Configure build environment (re-runs the 'cmake' command)";
    echo "t   Build and run the unit tests executable";
    echo "i   Install the plugin (samples / presets / pitch detection models)";
    echo "c   Clean any existing CMake files and build the plugin from scratch";
    echo "2   Use SPICE model for pitch detection";
    echo "3   Use CREPE model for pitch detection";
    echo "p   Sets the CMake build type to 'Production' (default is 'Debug')";
    echo "e   Enables GPU for tensorflow operations (applicable for SPICE/CREPE pitch detection models)";
    echo "g   Compile with GCC (default is Clang)";
    echo "f   Only run fast tests (i.e. no pitch detection tests)";
    echo "l   Use the debug log, which writes verbose messages to a local logfile";
    echo "u   Can be used to pass Catch2 CLI arguments into the unit test executable";
    echo "n   Clear terminal window and scrollback before building"
    echo "h   Print out a build script help message";
}

###########################################################################################
# CMake Functions
###########################################################################################

# ------------------------------- BUILD ARGUMENTS -------------------------------

catch2_args="";

make_parameters="plugin";

# ------------------------------- BUILD FUNCTIONS -------------------------------

cmake_piano960() 
{
    cmake_command_arguments="-DCMAKE_INSTALL_PREFIX=$MYSAMPLER_INSTALL_PREFIX -DPITCH_DETECTION=${PITCH_DETECTION_ALGO}";

    if [ "$ENABLE_GPU" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DTFLITE_ENABLE_GPU=ON";
    fi

    if [ "$USE_GCC" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++";
    fi

    if [ "$PRODUCTION" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Release";
    else
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Debug";
    fi

    if [ "$USE_LOG" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DUSE_LOG=ON";
    fi

    # ------------------------------

    if [ "$SILENT" = true ]; then
        cmake $MYSAMPLER_REPO $cmake_command_arguments > /dev/null;
    else
        verbose_print_stdin_command "cmake $MYSAMPLER_REPO $cmake_command_arguments";
        cmake $MYSAMPLER_REPO $cmake_command_arguments;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error_message "'cmake' command failed ('cmake $MYSAMPLER_REPO'). Exiting.";
    fi
}

make_piano960()
{
    if [ "$SILENT" = true ]; then
        make $make_parameters > /dev/null;
    else
        verbose_print_stdin_command "make $make_parameters";
        make $make_parameters;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error_message "'make' command failed. Exiting.";
    fi
}

###########################################################################################
# build setps
###########################################################################################

# 1) ================================= Parse CLI Options =================================

while getopts "vscit23pegatfalu:xbhn" option; do
    case $option in
      b) BUILD=true;;
      v) VERBOSE=true;;
      s) SILENT=true;;
      c) CLEAN_BUILD=true;;
      i) make_parameters="${make_parameters} install";;
      t) make_parameters="${make_parameters} unit-tests"; RUN_TESTS=true;;
      2) PITCH_DETECTION_ALGO="SPICE";;
      3) PITCH_DETECTION_ALGO="CREPE";;
      p) PRODUCTION=true;;
      e) ENABLE_GPU=true;;
      g) USE_GCC=true;;
      a) ABORT_AFTER_FIRST_TEST_FAILURE=true;;
      f) ONLY_RUN_FAST_TESTS=true;;
      l) USE_LOG=true;;
      u) catch2_args=${OPTARG};;
      n) bash $MYSAMPLER_REPO/Scripts/clear_terminal.sh;;
      h) print_help_message; exit;;
    esac
done

if [ $? -ne 0 ]; then
    exit_with_error_message "Invalid CLI Arguments: $?";
elif [ "$PRODUCTION" = true ]; then
    BUILD_DIRECTORY=$PRODUCTION_BUILD_DIRECTORY;
    BUILD_TYPE="Production";
else
    BUILD_DIRECTORY=$DEBUG_BUILD_DIRECTORY;
    BUILD_TYPE="Debug";
fi

# 2) ============================== Print Build Info Header ==============================

if [ "$USE_GCC" = true ]; then
    COMPILER_NAME="GCC";
else
    COMPILER_NAME="Clang"
fi

if [ "$RUN_TESTS" = true ]; then
    BUILD_TARGETS="plugin, unit-tests";
else
    BUILD_TARGETS="plugin";
fi

print_newline;
print_n_times 101 "="; print_newline;
print "|<><><><><><><><><><><><><><><><><><><><><><> My Sampler <><><><><><><><><><><><><><><><><><><><><><>"
print "| ";
print "| - Build Type: $BUILD_TYPE";
print "| "
print "| - Compiler: $COMPILER_NAME";
print "| ";
print "| - Build Target(s): $BUILD_TARGETS";
print "| ";
print "| - Build Directory: $BUILD_DIRECTORY";
print "| ";
print "| - Pitch Detection Algorithm: $PITCH_DETECTION_ALGO";
print "| ";
print -n "|"; print_n_times 50 "<>"; print_newline;
print_n_times 101 "="; print_newline;
print_newline;

# 3) =============================== Setup Build Directory ===============================

if [ ! -d "$ALL_BUILDS_DIRECTORY" ]; then
    BUILD=true;
    print_build_info "Creating Parent Directory For All Builds: $ALL_BUILDS_DIRECTORY"
    verbose_print_stdin_command "mkdir $ALL_BUILDS_DIRECTORY";
    mkdir $ALL_BUILDS_DIRECTORY;
fi

if [ "$CLEAN_BUILD" = true ]; then
    BUILD=true;
    print_build_info "Deleting Existing Build Directory: $BUILD_DIRECTORY"
    verbose_print_stdin_command "rm -rf $BUILD_DIRECTORY";
    rm -rf $BUILD_DIRECTORY;
fi

if [ ! -d "$BUILD_DIRECTORY" ]; then
    BUILD=true;
    print_build_info "Creating Build Directory: $BUILD_DIRECTORY"
    verbose_print_stdin_command "mkdir $BUILD_DIRECTORY";
    mkdir $BUILD_DIRECTORY;
fi

# 4) ========================= Configure CMake Build Environment =========================

working_directory=$(pwd);
verbose_print_stdin_command "cd $BUILD_DIRECTORY";
cd $BUILD_DIRECTORY;

if [ "$BUILD" = true ]; then
    print_header_message "Configuring CMake Build Environment"
    cmake_piano960;
fi

# 5) ============================= Build Plugin Executable(s) =============================

print_header_message "Building Plugin Executable(s)"
make_piano960 $make_parameters;

if [ $? -eq 0 ]; then
    print_newline;
    verbose_print_build_info "Successfully built MySampler to $BUILD_DIRECTORY";
else
    print_newline;
    verbose_print_build_info "Failed to build MySampler to $BUILD_DIRECTORY";
    exit;
fi

verbose_print_stdin_command "cd $working_directory";
cd $working_directory;

# 6) =================================== Run Unit Tests ===================================

if [ "$RUN_TESTS" = true ]; then

    print_header_message "Running Unit Tests"

    testQuery=$catch2_args;

    if [ "$ONLY_RUN_FAST_TESTS" = true ]; then
        testQuery="$catch2_args~[slow]";
    fi

    testArgs=$testQuery;

    if [ "$ABORT_AFTER_FIRST_TEST_FAILURE" = true ]; then
        testArgs="$testArgs --abort";
    fi
    if [ "$LIST_TESTS" = true ]; then
        testArgs="$testArgs --list-tests";
    fi

    verbose_print_stdin_command "$BUILD_DIRECTORY/Tests/unit-tests $testArgs";
    $BUILD_DIRECTORY/Tests/unit-tests $testArgs
fi

