#!/bin/bash

#
#
# Piano960 Build script 
#
#

PROJECT_NAME="Piano960"

PIANO960_REPO=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );

ALL_BUILDS_DIRECTORY=$PIANO960_REPO/Builds

DEBUG_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/debug-build

PRODUCTION_BUILD_DIRECTORY=$ALL_BUILDS_DIRECTORY/production-build

PIANO960_INSTALL_PREFIX=/usr/local

VERBOSE=false; # cli option

SILENT=false; # cli option

CLEAN_BUILD=false; # cli option

PITCH_DETECTION_ALGO="YIN";

DEBUG_BUILD=true;

ENABLE_GPU=false;

USE_GCC=false; # defaults to Clang

ABORT_AFTER_FIRST_TEST_FAILURE=false;

RUN_TESTS=false;

ONLY_RUN_FAST_TESTS=false;

LIST_TESTS=false;

USE_LOG=false;

CATCH2_ARGS="";

MAKE_PARAMETERS="Piano960Plugin";

###########################################################################################
# stdout helper functions
###########################################################################################

print()
{
    if [ "$SILENT" = false ]; then
        echo " # [BUILD::INFO] | $@"; 
        echo;
    fi
}

verbose_print() 
{
    if [ "$VERBOSE" = true ]; then 
        print "$@";
    fi
}

verbose_print_command()
{
    if [ "$VERBOSE" = true ]; then
        echo " # [BUILD::STDIN] | $@"; echo;
    fi
}

print_n_times()
{
    for i in $(seq $1); do echo -n $2; done
}

print_divider()
{
    print_n_times 50 "<>"; echo;
}

print_header_message()
{
    header_message="$@";
    message_length=${#header_message};
    line_length=100;
    indent=$((($line_length-$message_length-2)/2));

    if [ "$SILENT" = false ]; then
        echo;
        # print_n_times $line_length "-"; echo;
        echo -n "|";
        print_n_times $indent "-";
        echo -n " $header_message ";
        print_n_times $indent "-"; echo "|";
        # print_n_times $line_length "-"; echo;
        echo;
    fi
}

exit_with_error_message() 
{
    if [ "$SILENT" = false ]; then
        echo; 
        echo " # [BUILD::ERROR] | $@";
        echo; 
        exit;
    fi;
}

print_help_message() 
{
    echo "options:";
    echo "v   Print out verbose information";
    echo "s   Supress cmake output";
    echo "t   Build and run unit tests";
    echo "i   Add 'install' to the cmake command to install the samples";
    echo "c   Clean any existing and build the plugin from scratch";
    echo "2   use spice model for pitch detection";
    echo "3   use crepe model for pitch detection";
    echo "d   sets the CMAKE build type to Debug";
    echo "e   enables GPU for tensorflow operations";
    echo "g   compile with GCC";
    echo "f   only run fast tests (i.e. no pitch detection tests)";
    echo "l   turns on the logger, which writes verbose messages to a logfile";
    echo "u   can be used to pass arguments into unit test build";
}

###########################################################################################
# build functions
###########################################################################################

cmake_piano960() 
{
    cmake_command_arguments="-DCMAKE_INSTALL_PREFIX=$PIANO960_INSTALL_PREFIX -DPITCH_DETECTION=${PITCH_DETECTION_ALGO}";

    if [ "$ENABLE_GPU" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DTFLITE_ENABLE_GPU=ON";
    fi

    if [ "$USE_GCC" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++";
    fi

    if [ "$PRODUCTION" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Release";
    else
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Debug";
    fi

    if [ "$USE_LOG" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DUSE_LOG=ON";
    fi

    # ------------------------------

    if [ "$SILENT" = true ]; then
        cmake $PIANO960_REPO $cmake_command_arguments > /dev/null;
    else
        verbose_print_command "cmake $PIANO960_REPO $cmake_command_arguments";
        cmake $PIANO960_REPO $cmake_command_arguments;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error_message "'cmake' command failed ('cmake $PIANO960_REPO'). Exiting.";
    fi
}

make_piano960()
{
    if [ "$SILENT" = true ]; then
        make $MAKE_PARAMETERS > /dev/null;
    else
        verbose_print_command "make $MAKE_PARAMETERS";
        make $MAKE_PARAMETERS;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error_message "'make' command failed. Exiting.";
    fi
}

###########################################################################################
# build setps
###########################################################################################

# 1) ================== parse cli options ==================

while getopts "vscit23pegatfalu:xbh" option; do
    case $option in
      v) VERBOSE=true;;
      s) SILENT=true;;
      c) CLEAN_BUILD=true;;
      i) MAKE_PARAMETERS="${MAKE_PARAMETERS} install";;
      t) MAKE_PARAMETERS="${MAKE_PARAMETERS} unit-tests"; RUN_TESTS=true;;
      2) PITCH_DETECTION_ALGO="SPICE";;
      3) PITCH_DETECTION_ALGO="CREPE";;
      p) PRODUCTION=true;;
      e) ENABLE_GPU=true;;
      g) USE_GCC=true;;
      a) ABORT_AFTER_FIRST_TEST_FAILURE=true;;
      f) ONLY_RUN_FAST_TESTS=true;;
      l) USE_LOG=true;;
      u) CATCH2_ARGS=${OPTARG};;
      b) bash $PIANO960_REPO/Scripts/clear_terminal.sh;;
      h) print_help_message; exit;;
    esac
done

if [ $? -ne 0 ]; then
    exit_with_error_message "Invalid CLI Arguments: $?";
elif [ "$PRODUCTION" = true ]; then
    BUILD_DIRECTORY=$PRODUCTION_BUILD_DIRECTORY;
    BUILD_TYPE="Production";
else
    BUILD_DIRECTORY=$DEBUG_BUILD_DIRECTORY;
    BUILD_TYPE="Debug";
fi

# 2) ================== print header message ==================

echo;
print_n_times 105 "="; echo;
echo "|<><><><><><><><><><><><><><><><><><><><><><> Piano960 <><><><><><><><><><><><><><><><><><><><><><><><><> "
# print_n_times 100 "-"; echo;
echo "| ";
echo "| - Build Type: '$BUILD_TYPE'";
echo "| "
echo "| - Output Directory: '$BUILD_DIRECTORY'";
echo "| ";
echo -n "|"; print_n_times 52 "<>"; echo;
print_n_times 105 "="; echo;
echo;

# 3) ================== setup build directory ==================

if [ ! -d "$ALL_BUILDS_DIRECTORY" ]; then
    print "Creating Parent Directory For All Builds: $ALL_BUILDS_DIRECTORY"
    verbose_print_command "mkdir $ALL_BUILDS_DIRECTORY";
    mkdir $ALL_BUILDS_DIRECTORY;
fi

if [ "$CLEAN_BUILD" = true ]; then
    print "Deleting Existing Build Directory: $BUILD_DIRECTORY"
    verbose_print_command "rm -rf $BUILD_DIRECTORY";
    rm -rf $BUILD_DIRECTORY;
fi

if [ ! -d "$BUILD_DIRECTORY" ]; then
    print "Creating Build Directory: $BUILD_DIRECTORY"
    verbose_print_command "mkdir $BUILD_DIRECTORY";
    mkdir $BUILD_DIRECTORY;
fi

# 4) ================== build the plugin ==================

print_header_message "Configuring Build Environment"

working_directory=$(pwd);
verbose_print_command "cd $BUILD_DIRECTORY";
cd $BUILD_DIRECTORY;
cmake_piano960;

print_header_message "Building Plugin Executable"
make_piano960 $make_parameters;

if [ $? -eq 0 ]; then
    print "Successfully built Piano960 to $BUILD_DIRECTORY";
else
    print "Failed to build Piano960 to $BUILD_DIRECTORY";
    exit;
fi

verbose_print_command "cd $working_directory";
cd $working_directory;

# 5) ================== run the unit tests (if '-t' cli option was set) ==================

if [ "$RUN_TESTS" = true ]; then

    print_header_message "Running Unit Test Build"

    testQuery=$CATCH2_ARGS;

    if [ "$ONLY_RUN_FAST_TESTS" = true ]; then
        testQuery="$CATCH2_ARGS~[slow]";
    fi

    testArgs=$testQuery;

    if [ "$ABORT_AFTER_FIRST_TEST_FAILURE" = true ]; then
        testArgs="$testArgs --abort";
    fi
    if [ "$LIST_TESTS" = true ]; then
        testArgs="$testArgs --list-tests";
    fi

    verbose_print_command "$BUILD_DIRECTORY/Tests/unit-tests $testArgs";
    $BUILD_DIRECTORY/Tests/unit-tests $testArgs
fi

