#!/bin/bash

#
#
# Piano960 Build script 
#
#

PROJECT_NAME="Piano960"

PIANO960_REPO=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );

PIANO960_BUILD_DIRECTORY=$PIANO960_REPO/build

PIANO960_INSTALL_PREFIX=/usr/local

VERBOSE=false; # cli option

SILENT=false; # cli option

CLEAN_BUILD=false; # cli option

PITCH_DETECTION_ALGO="YIN";

DEBUG_BUILD=true;

ENABLE_GPU=false;

USE_GCC=false; # defaults to Clang

ABORT_AFTER_FIRST_TEST_FAILURE=false;

RUN_TESTS=false;

ONLY_RUN_FAST_TESTS=false;

LIST_TESTS=false;

USE_LOG=false;

echo_help_message() 
{
    echo "options:";
    echo "v   Print out verbose information";
    echo "s   Supress cmake output";
    echo "t   Build and run unit tests";
    echo "i   Add 'install' to the cmake command to install the samples";
    echo "c   Clean any existing and build the plugin from scratch";
    echo "2   use spice model for pitch detection";
    echo "3   use crepe model for pitch detection";
    echo "d   sets the CMAKE build type to Debug";
    echo "e   enables GPU for tensorflow operations";
    echo "g   compile with GCC";
    echo "f   only run fast tests (i.e. no pitch detection tests)";
    echo "l   turns on the logger, which writes verbose messages to a logfile";
}

pushd_silently() { command pushd "$@" > /dev/null; }
popd_silently()  { command popd "$@" > /dev/null; }

echo_stdin_message() { echo; echo "[STDIN]: $@"; echo; }
echo_build_message() { echo; echo "[BUILD MESSAGE]: $@"; echo; }
exit_with_error()    { echo; echo "[ERROR]: $@"; echo; exit; }

create_piano960_build_directory()
{
    echo_build_message "creating Piano960 build directory: $PIANO960_BUILD_DIRECTORY";

    if [ "$VERBOSE" = true ]; then echo_stdin_message "mkdir $PIANO960_BUILD_DIRECTORY"; fi
    mkdir $PIANO960_BUILD_DIRECTORY;

    if [ ! -d "$PIANO960_BUILD_DIRECTORY" ]; then
        exit_with_error "something went wrong while creating the build directory...";
    fi
}

cmake_piano960() 
{
    pushd_silently $PIANO960_BUILD_DIRECTORY;

    cmake_command_arguments="-DCMAKE_INSTALL_PREFIX=$PIANO960_INSTALL_PREFIX -DPITCH_DETECTION=${PITCH_DETECTION_ALGO}";

    if [ "$ENABLE_GPU" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DTFLITE_ENABLE_GPU=ON";
    fi

    if [ "$USE_GCC" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++";
    fi

    if [ "$DEBUG_BUILD" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Debug";
    else
        cmake_command_arguments="${cmake_command_arguments} -DCMAKE_BUILD_TYPE=Release";
    fi

    if [ "$USE_LOG" = true ]; then
        cmake_command_arguments="${cmake_command_arguments} -DUSE_LOG=ON";
    fi


    if [ "$VERBOSE" = true ]; then 
        echo_stdin_message "cmake $PIANO960_REPO $cmake_command_arguments";
        cmake $PIANO960_REPO $cmake_command_arguments;
    elif [ "$SILENT" = true ]; then
        cmake $PIANO960_REPO $cmake_command_arguments > /dev/null;
    else
        cmake $PIANO960_REPO $cmake_command_arguments;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error "'cmake' command failed ('cmake $PIANO960_REPO'). Exiting.";
    fi

    popd_silently;
}

make_piano960()
{
    pushd_silently $PIANO960_BUILD_DIRECTORY;

    make_command_arguments="$@";
    if [ "$VERBOSE" = true ]; then echo_stdin_message "make $make_command_arguments"; fi

    if [ "$SILENT" = true ]; then
        make $make_command_arguments > /dev/null;
    else
        make $make_command_arguments;
    fi

    if [ $? -ne 0 ]; then
        exit_with_error "'make' command failed. Exiting.";
    fi

    popd_silently;
}

# 1) --- handle user input ---

# TODO: support full word options (e.g. --verbose)

make_parameters="Piano960Plugin" # this gets passed to the 'make' command
function add_make_parameter() { make_parameters="${make_parameters} $@"; }

while getopts "hvscit23degatfal" option; do
   case $option in
      h) echo_help_message; exit;;                          # -h : display help message
      v) VERBOSE=true;;                                     # -v : turn on verbose mode
      s) SILENT=true;;                                      # -s : turn on silent mode
      c) CLEAN_BUILD=true;;                                 # -c : make clean build
      i) add_make_parameter "install";;                     # -i : install samples
      t) add_make_parameter "unit-tests"; RUN_TESTS=true;;  # -t : build and run unit tests
      2) PITCH_DETECTION_ALGO="SPICE";;                     # -2 : use spice model for pitch detection
      3) PITCH_DETECTION_ALGO="CREPE";;                     # -3 : use crepe model for pitch detection
      d) DEBUG_BUILD=false;;
      e) ENABLE_GPU=true;;
      g) USE_GCC=true;;
      a) ABORT_AFTER_FIRST_TEST_FAILURE=true;;
      f) ONLY_RUN_FAST_TESTS=true;;
      l) USE_LOG=true;;
   esac
done

# 2) --- create build files ---

if [ -d "$PIANO960_BUILD_DIRECTORY" ] && [ "$CLEAN_BUILD" = true ]; then
    if [ "$VERBOSE" = true ]; then 
        echo_stdin_message "rm -rf" $PIANO960_BUILD_DIRECTORY; 
    fi

    rm -rf $PIANO960_BUILD_DIRECTORY;
fi

if [ ! -d "$PIANO960_BUILD_DIRECTORY" ]; then 
    create_piano960_build_directory;
    cmake_piano960;
elif [ "$CLEAN_BUILD" = true ]; then
    cmake_piano960;
fi

# 3) --- build the executable(s) ---

make_piano960 $make_parameters;

if [ "$RUN_TESTS" = true ]; then
    # if -t option was set, run the newly built unit tests 
    testArgs="";

    if [ "$ONLY_RUN_FAST_TESTS" = true ]; then
        testArgs="$testArgs ~[slow]";
    fi

    if [ "$ABORT_AFTER_FIRST_TEST_FAILURE" = true ]; then
        testArgs="$testArgs --abort";
    fi

    if [ "$VERBOSE" = true ]; then
        testArgs="$testArgs -?";
    fi

    if [ "$LIST_TESTS" = true ]; then
        testArgs="$testArgs --list-tests";
    fi

    $PIANO960_BUILD_DIRECTORY/Tests/unit-tests $testArgs;
fi

echo_build_message "Successfully built Piano960 to" $PIANO960_BUILD_DIRECTORY;

