#!/bin/bash

SCRIPT=$(realpath "$0");
SCRIPT_DIR=$(dirname "$SCRIPT");
REPO_PATH=$(dirname "$SCRIPT_DIR");
DEFAULT_PRESETS_FILEPATH=$REPO_PATH/presets.json
INSTALLED_PRESETS_FILEPATH=/usr/local/include/Piano960/presets.json

rm $INSTALLED_PRESETS_FILEPATH;
cp $DEFAULT_PRESETS_FILEPATH $INSTALLED_PRESETS_FILEPATH;