/* pitch_detection_v2.cpp */

/** Notes
 * 
 *  -- tensorflow's c++ interface seems to be the path of least resistance, since we're loading
 *     protobuf files generated by tensorflow, but it comes at the cost of build complexity
 *  -- https://stackoverflow.com/questions/56837288/tensorflow-lite-c-api-example-for-inference
 *  -- model is currently installed to /usr/local by cmake, but this doesn't seem right. Investigate.
 *  -- SPICE Model: https://www.tensorflow.org/hub/tutorials/spice
 *  -- "The SPICE model needs as input an audio file at a sampling rate of 16kHz 
 *      and with only one channel (mono).
 **/

#include <cassert>

#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/tools/gen_op_registration.h"
